---
title: ""
output: 
  html_document:
    css: !expr here::here("www", "web_report_trust.css")
---

```{=html}
<style>
@import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300&display=swap');
</style>
```
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Merriweather" />

<center>
# Glossary
</center>

```{r, echo = FALSE}
cur_date_utc <- Sys.Date()
cur_date <- sprintf(
  "%s %d, %s",
  format(cur_date_utc, "%B"),
  as.integer(format(cur_date_utc, "%d")),
  format(cur_date_utc, "%Y")
)
```

<center>**Last Updated:** `r cur_date`</center>
<br><br>

*This glossary provides the definition of key terms as used in the Dashboard.*

- **Adopted Budget:** authorized funds for a specific use. For ARPA SLFRF programs (see definition below), governments report on expenditures relative to the adopted budget for specific programs. The authorized budget amount may vary from a program’s original allocated amount as budget priorities shift.

- **Affordable Housing:** investments aimed at preserving or creating affordable housing units.

- **Allocations:** funds originally earmarked for specific uses in government plans, such as COVID-19 recovery plans. Allocations to programs may shift over time, and may vary from the final dollar amount committed to in a government’s adopted budget.

- **Alternative Emergency Response:** services such as sobering centers, behavioral health programs, and implementation of the 211 call line, a referral line for human and social services.

- **American Rescue Plan Act (ARPA):** a $1.9 trillion economic stimulus bill addressing economic recovery from the COVID-19 pandemic, passed on March 11, 2021. ARPA includes the Coronavirus State and Local Fiscal Recovery Funds (SLFRF) program, which directed $350 billion of flexible funds to states, counties, tribal governments, and localities.

- **Appropriations:** the amount of funding committed by the federal government to the city, county, or state for a given program.

- **Assistance for Returning Residents/Justice Involved People:** services aimed at assisting people returning from incarceration or who are involved in the criminal justice system.

- **Assistance for Specific Populations:** targeted programs for specific populations, such as older adults, veterans, people with disabilities, or people experiencing homelessness.

- **Awards:** infrastructure funds that have been delivered by the federal government to specific recipients. Agencies will announce an expected funding allocation for a given federal program and recipient, and then will deliver the funds to that recipient via awards. For example, an agency may announce a 2-year allocation and then deliver that funding via two different annual awards. In some cases, the total amount of the awards to a recipient may differ from the original allocation.

- **Broadband:** programs that provide or enhance broadband internet access.

- **Capacity Building:** funds to support government agencies and non-governmental organizations’ staffing to sustainably deliver and scale up core services.

- **Community Development:** investments aimed at developing or maintaining community vibrancy.

- **Community Investment:** programs that address a community’s collective needs and engage the community in developing sustainable solutions to communal challenges. Programs include infrastructure support, small business and economic support, and education and health services.

- **Community Safety:** programs and initiatives that seek to prevent or reduce violence, assist people in reintegrating into their community following incarceration or while they are involved in the criminal legal system, aid people who have been victims of violence, and implement alternative emergency response services.

- **Consolidated Appropriations Act 2021:** a $2.3 trillion spending bill passed on December 21, 2020, that includes the Coronavirus Response and Relief Supplemental Appropriations Act (CRRSAA), which provided additional stimulus relief for the COVID-19 pandemic.

- **Coronavirus Aid, Relief, and Economic Security Act (CARES):** a $2.2 trillion economic stimulus bill addressing economic recovery from the COVID-19 pandemic, passed on March 27, 2020. The CARES Act included direct cash payments to individuals, expanded unemployment benefits, and business assistance funds.

- **Criminal Justice Reform:** programs that address structural issues in criminal justice systems, such as youth diversion programs and revisions to budgets and case management.

- **Direct Cash Assistance:** unrestricted cash flowing directly to individuals and families.

- **Earmarks:** funds provided by Congress for specific projects, not to be allocated by federal agencies through a competitive process.

- **Electric Vehicle Infrastructure:** equipment that supports the use of electric vehicles, such as battery charging stations and rapid charging stations.

- **Employment Opportunities:** funding allocations that will result in job creation.

- **Expenditures:** funds that have been spent or paid out.

- **Expiration:** the date at which funds are no longer available for expenditure. Expiration dates vary by program.

- **General Fiscal Support:** flexible funds available for broad COVID-19 economic recovery efforts.

- **Homeowners Assistance:** programs that support property owners in maintaining their homeowner status and help non-homeowners pursue ownership.

- **Homelessness Supports/Prevention:** programs and wraparound supports for people experiencing or at risk of experiencing homelessness.

- **Household Investment:** programs that provide targeted support for households, such as direct cash assistance and legal services, and expand awareness of and access to public services.

- **Household Supportive Services:** services aimed at addressing household stability, such as unemployment insurance, energy affordability assistance, and early education assistance.

- **Housing:** programs addressing a range of needs for renters, homeowners, and people experiencing homelessness, including affordability, stability, shelter solutions, and temporary and permanent supportive housing services.

- **Infrastructure:** programs that support organizational structures and facilities, such as buildings, roads, highways, and bridges.

- **Job Training:** programs aimed at equipping people with the necessary skills to obtain and maintain jobs in specific industries.

- **Obligations:** committed funds for property and services, such as through contracts, subawards, and other payment transactions.

- **Rail:** rail infrastructure includes tracks, other infrastructure surrounding tracks, tunnels, bridges, stations and terminals, platforms, train control and signaling systems, and associated machinery and equipment.

- **Rebates:** funds paid by the federal government to reimburse eligible recipients for allowable expenditures.

- **Renter Assistance:** programs supporting people and households living in rental housing.

- **Revenue Replacement:** funds that replace government revenue lost during the pandemic to preserve government staffing and essential services. Under ARPA, all recipients of SLFRF dollars are authorized to classify at least $10 million of their allocations as revenue replacement.

- **Revolving Loan Funds:** a pool of money that uses interest and principal payments on old loans to issue new loans.

- **Small Business:** programs that support small businesses in maintaining and expanding operations.

- **Targeted Economic Assistance:** financial and programmatic supports for specific demographics, such as veterans or immigrants.

- **Traffic Safety:** programs that protect pedestrians, cyclists, motorists, vehicle passengers, and other passengers of on-road public transport.

- **Transportation:** programs that support transit systems and the infrastructure that supports them, including vehicles, buses, trains, bicycles, and pedestrian walkways.

- **Utility Assistance:** assistance to households to cover utility costs, including water.

- **Victim Support Services:** services and supports for victims of violent crime and their families, including mental health supports, crisis intervention, support with accessing crime victim compensation, housing, and food.

- **Violence Prevention/Reduction:** funding aimed at preventing or reducing violence, including violence intervention programming and support for community groups.

- **Water Infrastructure:** all the man-made and natural features that move and treat water.

- **Workforce Supportive Services:** programs that connect people to employment opportunities.

- **Workforce Sustainability:** assistance to maintain the existing workforce.